# Generated by Django 4.2.2 on 2024-09-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('big_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Article',
        ),
    ]
